### ISSUE TITLE
having issues installing the backend

### ISSUE THREAD

**Issue by jamesdalg** [cubimedrub/macworp#7]
I'm having issues installing the backend. This seems like a great idea and I'd like to get it to work, but if you can help me chase down this error, this would be helpful.

```
(nfcloud) jd@oban:~/code/nf/nf-cloud$ pip install -e ./backend/
Obtaining file:///media/jd/bfbdb6dc-6302-491f-932d-dc2881ea6091/code/nf/nf-cloud/backend
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting gunicorn@ git+https://github.com/benoitc/gunicorn.git@ff58e0c6da83d5520916bc4cc109a529258d76e1#egg=gunicorn (from nf-cloud-backend==1.0.0)
  Cloning https://github.com/benoitc/gunicorn.git (to revision ff58e0c6da83d5520916bc4cc109a529258d76e1) to /tmp/pip-install-dz4e0phd/gunicorn_a6ffd01cc77544b986b19a498809817e
  Running command git clone --filter=blob:none --quiet https://github.com/benoitc/gunicorn.git /tmp/pip-install-dz4e0phd/gunicorn_a6ffd01cc77544b986b19a498809817e
  Running command git rev-parse -q --verify 'sha^ff58e0c6da83d5520916bc4cc109a529258d76e1'
  Running command git fetch -q https://github.com/benoitc/gunicorn.git ff58e0c6da83d5520916bc4cc109a529258d76e1
  Running command git checkout -q ff58e0c6da83d5520916bc4cc109a529258d76e1
  Resolved https://github.com/benoitc/gunicorn.git to commit ff58e0c6da83d5520916bc4cc109a529258d76e1
  Preparing metadata (setup.py) ... done
Collecting eventlet<0.34,>=0.33 (from nf-cloud-backend==1.0.0)
  Using cached eventlet-0.33.3-py2.py3-none-any.whl (226 kB)
Collecting Flask<3,>=2 (from nf-cloud-backend==1.0.0)
  Using cached Flask-2.3.2-py3-none-any.whl (96 kB)
Collecting Flask-Caching<3,>=2 (from nf-cloud-backend==1.0.0)
  Using cached Flask_Caching-2.0.2-py3-none-any.whl (28 kB)
Collecting Flask-Cors<4,>=3 (from nf-cloud-backend==1.0.0)
  Using cached Flask_Cors-3.0.10-py2.py3-none-any.whl (14 kB)
Collecting Flask-Login<0.7.0,>=0.6.1 (from nf-cloud-backend==1.0.0)
  Using cached Flask_Login-0.6.2-py3-none-any.whl (17 kB)
Collecting flask-socketio<6,>=5 (from nf-cloud-backend==1.0.0)
  Using cached Flask_SocketIO-5.3.4-py3-none-any.whl (17 kB)
Collecting jsonschema<5,>=4 (from nf-cloud-backend==1.0.0)
  Using cached jsonschema-4.18.4-py3-none-any.whl (80 kB)
Collecting kombu<6,>=5 (from nf-cloud-backend==1.0.0)
  Using cached kombu-5.3.1-py3-none-any.whl (198 kB)
Collecting markupsafe==2.0.1 (from nf-cloud-backend==1.0.0)
  Using cached MarkupSafe-2.0.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (30 kB)
Requirement already satisfied: mergedeep<2,>=1 in /home/jd/mambaforge/envs/nfcloud/lib/python3.10/site-packages (from nf-cloud-backend==1.0.0) (1.3.4)
Collecting oauthlib<4,>=3 (from nf-cloud-backend==1.0.0)
  Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)
Collecting peewee<4,>=3 (from nf-cloud-backend==1.0.0)
  Using cached peewee-3.16.2.tar.gz (2.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting peewee-migrate>=1.1.6 (from nf-cloud-backend==1.0.0)
  Using cached peewee_migrate-1.11.1-py3-none-any.whl (18 kB)
Requirement already satisfied: pika<2,>=1 in /home/jd/mambaforge/envs/nfcloud/lib/python3.10/site-packages (from nf-cloud-backend==1.0.0) (1.3.2)
Collecting piwikapi==0.3 (from nf-cloud-backend==1.0.0)
  Using cached piwikapi-0.3.tar.gz (24 kB)
  Preparing metadata (setup.py) ... done
Collecting psycopg2-binary<3,>=2 (from nf-cloud-backend==1.0.0)
  Using cached psycopg2_binary-2.9.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
Collecting pyjwt<3,>=2 (from nf-cloud-backend==1.0.0)
  Using cached PyJWT-2.7.0-py3-none-any.whl (22 kB)
Collecting PyYAML<6,>=5 (from nf-cloud-backend==1.0.0)
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      /tmp/pip-build-env-mr8qjyfs/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
      
              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.
      
              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/home/jd/mambaforge/envs/nfcloud/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/jd/mambaforge/envs/nfcloud/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/jd/mambaforge/envs/nfcloud/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-mr8qjyfs/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-mr8qjyfs/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-mr8qjyfs/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/tmp/pip-build-env-mr8qjyfs/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-mr8qjyfs/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-mr8qjyfs/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-mr8qjyfs/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-mr8qjyfs/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-mr8qjyfs/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-mr8qjyfs/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 314, in run
          self.find_sources()
        File "/tmp/pip-build-env-mr8qjyfs/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
          mm.run()
        File "/tmp/pip-build-env-mr8qjyfs/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/tmp/pip-build-env-mr8qjyfs/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-mr8qjyfs/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-mr8qjyfs/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-mr8qjyfs/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 201, in get_source_files
        File "/tmp/pip-build-env-mr8qjyfs/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by di-hardt** [comment]
Thanks for reporting. Seems like you're missing libyaml.   
Have a look in https://github.com/mpc-bioinformatics/nf-cloud/blob/master/environment.yml . There are currently two C-dependencies to match: libyaml and libpq. Depending on your  distribution the necessary header files may located in another package e.g. libyaml-dev for Ubuntu.

**Comment by di-hardt** [comment]
Close due to inactivity
